"""initial

Revision ID: 9625980cea9b
Revises: 
Create Date: 2026-05-06 10:39:58.767239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9625980cea9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_feedback_menu_id')
        batch_op.drop_index('idx_feedback_user_id')
        batch_op.drop_constraint('feedback_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('feedback_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'menus', ['menu_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('menu_options', schema=None) as batch_op:
        batch_op.drop_index('idx_options_menu_id')
        batch_op.drop_constraint('menu_options_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'menus', ['menu_id'], ['id'])

    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.alter_column('is_locked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_menus_date')
        batch_op.drop_index('idx_menus_deadline')
        batch_op.drop_index('idx_menus_meal_type')
        batch_op.drop_constraint('menus_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_users_email')
        batch_op.drop_index('idx_users_role')

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('voted_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_votes_menu_id')
        batch_op.drop_index('idx_votes_option_id')
        batch_op.drop_index('idx_votes_user_id')
        batch_op.drop_index('idx_votes_voted_at')
        batch_op.drop_constraint('votes_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('votes_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('votes_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'menu_options', ['option_id'], ['id'])
        batch_op.create_foreign_key(None, 'menus', ['menu_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('votes_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('votes_ibfk_2', 'menus', ['menu_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('votes_ibfk_3', 'menu_options', ['option_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_votes_voted_at', ['voted_at'], unique=False)
        batch_op.create_index('idx_votes_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_votes_option_id', ['option_id'], unique=False)
        batch_op.create_index('idx_votes_menu_id', ['menu_id'], unique=False)
        batch_op.alter_column('voted_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_role', ['role'], unique=False)
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('menus_ibfk_1', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
        batch_op.create_index('idx_menus_meal_type', ['meal_type'], unique=False)
        batch_op.create_index('idx_menus_deadline', ['deadline'], unique=False)
        batch_op.create_index('idx_menus_date', ['date'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('is_locked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('menu_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('menu_options_ibfk_1', 'menus', ['menu_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_options_menu_id', ['menu_id'], unique=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('feedback_ibfk_2', 'menus', ['menu_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('feedback_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_feedback_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_feedback_menu_id', ['menu_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('rating',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
